# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: UI5 app tests

# on:
#   pull_request:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#       - name: update chrome
#         run: |
#           sudo apt-get update
#           sudo apt-get --only-upgrade install google-chrome-stable
#           # check chrom version
#           google-chrome --version

#       - name: Get yarn cache directory path
#         id: yarn-cache-dir-path
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - uses: actions/cache@v2
#         id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
#         with:
#           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#           key: ${{ runner.os }}-yarn-cfdestination-${{ hashFiles('**/yarn.lock') }}
#           # restore-keys: |
#           #   ${{ runner.os }}-yarn-

#       - uses: actions/checkout@v2

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: install dependencies # only when not cached
#         # if: steps.yarn-cache.outputs.cache-hit != 'true'
#         run: yarn install --frozen-lockfile --ignore-engines

#       # runs opa5 (+ qunit) tests
#       - run: yarn test:opa5-ci

#       # runs wdi5 + uiveri5 tests
#       - run: yarn test:ci
